### ISSUE TITLE
Country IRL no longer working in 2.1.6beta6 (worked up to 2.1.5)

### ISSUE THREAD

**Issue by Gavin-A92** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#1]
Updated Custom Component no longer working as was in 2.1.5.
Looking at logs (below) I believe this is down to "new" feature around removing the need for Country parameter. IRL (Ireland) as a country has worked 100% perfectly up to now but no longer works in this beta. Understand this is (and never was) technically "supported" but have found it to work pretty much perfectly up to this version.
"Buttons" (change channel, etc) work as expected but the boxes (1x Q 2TB and 2 x Mini) are not correctly detected by the component (and report as off despite being on (and controllable too))

**To Reproduce**
No steps to reproduce per se, once upgraded this was noticed.
Notwithstanding support for GBR/ITA this has worked fine for IRL up to 2.1.6
Media Player(s) are detected but functionality is reduced.

**config.yaml extract**

```
media_player:
  - platform: skyq
    host: 192.168.10.241
    name: SkyQ Sitting Room
    room: Sitting Room
    config_directory: '/config/'
    generate_switches_for_channels: true
    sources:
      DisneyJnr: '6,0,7'                                                        
      DisneyJnr+1: '6,0,8'                                                      
      CHup: 'channelup'
      CHdn: 'channeldown'
      Select: 'select'                                                          
      Up: 'up'                                                                  
      Down: 'down'                                                              
      Left: 'left'                                                              
      Right: 'right'                                                            
      I: 'i'                                                                    
      Dismiss: 'dismiss'                                                        
      Sidebar: 'Sidebar'                                                        
      Home: 'home'                                                              
      TVGuide: 'tvguide'                                                        
      Sky: 'sky'                                                                
      Record: 'record'      
```                                                    
````
**Output of HA logs**
Paste the relavant output of the HA log here.

Think this is the relevant errors from the log........
2020-05-05 22:43:40 ERROR (SyncWorker_16) [pyskyqremote.skyq_remote] E0040 - Invalid country: 192.168.10.241 : IRL : No module named 'pyskyqremote.country.remote_ie'
2020-05-05 22:43:40 ERROR (SyncWorker_10) [pyskyqremote.skyq_remote] E0040 - Invalid country: 192.168.10.242 : IRL : No module named 'pyskyqremote.country.remote_ie'
2020-05-05 22:43:40 ERROR (SyncWorker_7) [pyskyqremote.skyq_remote] E0040 - Invalid country: 192.168.10.243 : IRL : No module named 'pyskyqremote.country.remote_ie'
2
