### ISSUE TITLE
Play nice with Alexa

### ISSUE THREAD

**Issue by Robjgt** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#110]
First off congats on an excellent home assistant add-on especially enthusiastic about the opportunity to expose the channel selection functions to my voice assistant.

I note the documentation covers integration with the Google Voice assistant however I found setting up with Alexa was easily achieved by exposing the channel switches via the Philips hue emulator integration however this method seems to have uncovered an annoying hickup related to the way the voice assistant operates.

Whenever any of the channel  switches are activated via a voice command my skyq box immediately responds with no issues but following each channel change the Alexa responds annoyingly with 'device unresponsive' every time.

I note that manually operating the channel switches via home assistants web interface that the switches are toggled back to the off state very quickly after being toggled on and I think this might be the cause of the unwanted responses.

 Alexa seems to be fooled into detecting an error because after toggling a switch to the on state it appears to re check the state of the switch only to find it not be in the expected state thus it deems the switch to be unresponsive'.

My feature request is to attempt to make the add-on more compatible with Alexa and suppress the unwanted Alexa response by introducing a small delay before resetting the channel switches the off state such that Alexa is happy that  the switch has indeed responded to the on command.

Best Regards
Rob

**Comment by RogerSelwyn** [comment]
I’m on holiday at the moment so will I look at it in more detail in about 10 days. It might be within your control, or at least you can look at the switch yaml and create a new file with modified code to try and fix the problem because I’m pretty sure it will be controlled by the yaml.

**Comment by RogerSelwyn** [comment]
Just looking at this I created a switch like the below (based on what is generated). Could you do the same and try it with your Alexa setup. Basically I've add a 10 second delay before it switches off. If that works for you, I can add it to the generated code. You may need to change the entity and source name from the one below, or just copy from the generated yaml and update the turn_on section.

```
switch:
  - platform: template
    switches:
      skyq_bbconesouthdefaultroom:
        value_template: '{{"off"}}'
        friendly_name: 'BBC One South in the Default Room'
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.sky_q_mini
              source: 'BBC One South'
          - delay:
              seconds: 10
        turn_off:
          stop:
```
