### ISSUE TITLE
[BUG] Sky Sports Football Auto Switch Generation

### ISSUE THREAD

**Issue by onemico** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#15]
**Describe the bug**  
So just for info, when using switch auto generation with Sky Sports Football in the UK, it has the channel list as SkySp F'ball HD

The ' as added to the switch name and causes the config to fail to load.  The same issue then occurs in friendly name and source, and you need to put full "" marks on it.

Currently it deploys like:
```yaml
    skyq_skyspf'ballhdlivingroom:
      value_template: '{{"off"}}'
      friendly_name: 'SkySp F'ball HD in the Living Room'
      turn_on:
        service: media_player.select_source
        data:
          entity_id: media_player.sky
          source: 'SkySp F'ball HD'
      turn_off:
        service: script.placeholder
````
I had to edit it like:

```yaml
    skyq_skyspfballhdlivingroom:
      value_template: '{{"off"}}'
      friendly_name: "SkySp F'ball HD in the Living Room"
      turn_on:
        service: media_player.select_source
        data:
          entity_id: media_player.sky
          source: "SkySp F'ball HD"
      turn_off:
        service: script.placeholder
````

Also, if you then edit and leave auto generation on, this re-writes the file and causes config failure on each startup, so once edited you need to disable the auto switch generation feature.

**To Reproduce**  
1. Select Sky Sports F'Ball HD as a channel
2. enable auto switch generation for channels

**Expected behavior**  
N/A

**Screenshots**  
N/A

**Component versions**  
1. What version of SkyQ component are you using? 2.2.3
2. What was the last version where the problem was not shown? Unsure, only started using auto generation with this version

**Your configuration**  
How have you setup your devices, by UI or YAML? UI

**Output of HA logs**  
N/A (apologies, I haven't saved them since I manually edited config)

**Additional context**  
N/A
