### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by RogerSelwyn** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#17]
**Is your feature request related to a problem? Please describe.**  
From harry1 - [Community Forum](https://community.home-assistant.io/t/custom-component-skyq-media-player/140306/448)

Would it be possible to add a volume_up and volume_down service to the skyq media players like the universal media player does for use with homekit?

In a similar config as this:

 ```
   volume_up:
      service: switch.turn_on
      data:
        entity_id: switch.living_room_volume_up
    volume_down:
      service: switch.turn_on
      data:
        entity_id: switch.living_room_volume_down
```

**Additional context**  
https://github.com/home-assistant/core/blob/c994904e755431c0101e6d49855c8822f033cf8b/homeassistant/components/universal/media_player.py
