### ISSUE TITLE
Failed to call service media_player

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#27]
I’m getting an error 👍 
Failed to call service media_player/play_media. Async_play_media() got an unexpected keyword argument ‘extra’

I’m not sure if it came with the latest home assistant core install or your latest beta (which I have rolled back and it didn’t fix it )

Any thoughts on cause ?

Thanks.

**Comment by RogerSelwyn** [comment]
Did you restart after rolling back? What version HA are you on? How is your config setup (what channel and custom sources)? Was the error triggered by you clicking on a button in Mini Media Player button, or from media browser?

**Comment by B-Hartley** [comment]
I’m just trying again, I’ve done the rollback again and I’m doing a full host restart just to make sure.
The native play pause within the media player for example works fine.
But my buttons that cause actions by calling the play_media service don’t work.

The error is caused by me clicking on a button that is doing this.....


```
                  - entity: media_player.lounge_skytv
                    hold_action:
                      action: call-service
                      haptic: success
                      repeat: 250
                      service: media_player.play_media
                      service_data:
                        entity_id: media_player.lounge_skyq
                        media_content_id: left
                        media_content_type: skyq
```

HA: 115.4
