### ISSUE TITLE
[BUG] media.player changes name

### ISSUE THREAD

**Issue by enry86cami** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#41]
I updated to the last version, the problem is that:
about each a day the media_player changes the name: sometimes works with media_player.skyq_living_room, sometimes with media_player.sky.
And in my config folder I have the skyqDefaultRoom.yaml file.

This is my configuration.yaml:
```yaml
media_player:
 - platform: skyq
   name: sky
   host: 192.168.0.12
   sources:
      SkyTG: '1,0,0'
      SkySport: '2,0,0'
      SkyMotori: '4,1,8'
   generate_switches_for_channels: true
````

![image](https://user-images.githubusercontent.com/54316185/105966954-931cff00-6085-11eb-9834-c4c5b88290fc.png)
For example now is working with the name: media_player.skyq_living_room but, as you can see the name inside configurationyaml is sky. 

In development tools I see only media_player.skyq_living_room
![image](https://user-images.githubusercontent.com/54316185/105967327-0161c180-6086-11eb-9771-86bcfd1a17a1.png)
