### ISSUE TITLE
[BUG] If Switch name contains a "+" or "." symbol, HA returns errors / invalid config

### ISSUE THREAD

**Issue by sira87** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#45]
**Describe the bug**  
If switch name contains a "." HA returns error

**To Reproduce**  
1. Enable Channel Switches creation

**Expected behavior**  
Channels Switches should be created without errors in the naming scheme.

**Screenshots**  
**-**

**Component versions**  
1. What version of SkyQ component are you using?
**2.5.2**
2. What was the last version where the problem was not shown?
**unknown**

**Your configuration**  
How have you setup your devices, by UI or YAML? 
**UI**

**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  
```yaml
switch skyq:
- platform: template
  switches: !include skyqSala.yaml
````

**skyqSala.yaml**  (auto-generated by SkyQ integration UI enabling switch generation)
```yaml
(...)
    skyq_foxcrimehdsala:
      value_template: '{{"off"}}'
      friendly_name: 'Fox Crime HD in the Sala'
      turn_on:
        service: media_player.select_source
        data:
          entity_id: media_player.sky_q
          source: 'Fox Crime HD'
      turn_off:
        service: script.placeholder
    skyq_crime+inv.hdsala:
      value_template: '{{"off"}}'
      friendly_name: 'Crime + Inv. HD in the Sala'
      turn_on:
        service: media_player.select_source
        data:
          entity_id: media_player.sky_q
          source: 'Crime + Inv. HD'
      turn_off:
        service: script.placeholder
    skyq_discovery+1sala:
      value_template: '{{"off"}}'
      friendly_name: 'Discovery +1 in the Sala'
      turn_on:
        service: media_player.select_source
        data:
          entity_id: media_player.sky_q
          source: 'Discovery +1'
      turn_off:
        service: script.placeholder
    skyq_skyuno+1hdsala:
      value_template: '{{"off"}}'
      friendly_name: 'Sky Uno +1 HD in the Sala'
      turn_on:
        service: media_player.select_source
        data:
          entity_id: media_player.sky_q
          source: 'Sky Uno +1 HD'
      turn_off:
        service: script.placeholder
    skyq_fox+1sala:
      value_template: '{{"off"}}'
      friendly_name: 'Fox +1 in the Sala'
      turn_on:
        service: media_player.select_source
        data:
          entity_id: media_player.sky_q
          source: 'Fox +1'
      turn_off:
        service: script.placeholder
(...)
````
**Output of HA logs**  
````
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420
Integration: Hass.io (documentation, issues)
First occurred: 14:20:38 (1 occurrences)
Last logged: 14:20:38

Invalid config for [switch.template]: invalid slug skyq_crime+inv.hdsala (try skyq_crime_inv_hdsala) for dictionary value @ data['switches']. Got OrderedDict([('skyq_pausesala', OrderedDict([('value_template', '{{"off"}}'), ('friendly_name', 'pause in the Sala'), ('turn_on', OrderedDict([('service', 'media_player.media_pause'), ('data', OrderedDict([('entity_id', 'media_player.sky_q')]))])), ('turn_off', OrderedDict([('service', 'script.placeholder')]))])), ('skyq_playsala', OrderedDict([('value_template', '{{"off"}}'), ('friendly_name', 'play in the Sala'), ('turn_on', OrderedDict([('service', 'media_player.media_play'), ('data', Orde.... (See ?, line ?).
````
**Additional context**  
Entity names for channel switches that contains a "+" or "." symbol makes HA returns errors in home assistant. Substituting the symbols with "_" in the config files solves the issue.
