### ISSUE TITLE
[BUG] SkyQ Media Player is not correctly exposed to Google Assistant

### ISSUE THREAD

**Issue by snakuzzo** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#58]
**Describe the bug**  
I don't know if this is a bug of this custom component.
Media player entities created using other integrations (eg. Xbox) is exposed to Google Assistant correctly and works fine
SkyQ Media player entity on Google Assistant is not exposed correctly and it doesn't work.

**To Reproduce**  
Expose skyq media player to Google using [Google Assistant Integration](https://www.home-assistant.io/integrations/google_assistant/)

**Expected behavior**  
I expect to control (on/off) correctly my SkyQ

**Screenshots**  
**SkyQ media player**
![image](https://user-images.githubusercontent.com/7205371/127781776-e773b409-0d23-4702-a0dd-f2153233a1fe.png)

**Working media player**
![image](https://user-images.githubusercontent.com/7205371/127781787-64e6a2d7-c4ff-43c6-8338-fbc17f16b264.png)

**Component versions**  
1. What version of SkyQ component are you using? 2.6.1
2. What was the last version where the problem was not shown? I don't know

**Your configuration**  
How have you setup your devices, by UI or YAML? YAML

**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  
```yaml
media_player:
- platform:  skyq
  name: Sky
  host: 192.168.1.15
  #output_programme_image: False
  live_tv: False
  country: ITA
  #generate_switches_for_channels: true
  sources:
    SkyTG24HD_100: '1,0,0'
    Rai1_101: '1,0,1'
    Rai2_102: '1,0,2'
    Rai3_103: '1,0,3'
    Rete4HD_104: '1,0,4'
    ...
    ...
    many other channels
````

and this is how I expose media players...

```yaml
project_id: xxxxxxxxxxxxxx
service_account: !include Google_HomeAssistant-xxxxxxxx.json
report_state: true
expose_by_default: true
exposed_domains:
  - light
  - switch
  - cover
  - scene
entity_config:
  media_player.xbox:
    name: Xbox
    expose: true
  media_player.sky:
    name: Sky
    expose: true
```

**Output of HA logs**  
-

**Additional context**  
-

**Comment by RogerSelwyn** [comment]
I will take a look at this, but I suspect it isn't so much a bug as something I haven't built in yet. I don't use Google Assistant so it maybe a challenge to figure it out (I don't even have an Android phone). 

No promises how quick I look at it, but I will look at it at some point in the next few weeks.

**Comment by RogerSelwyn** [comment]
Been trying to do some research, to be honest I have no idea what it is GA is needing for it to work. If there is anyway for you to see in your environment as to what it needs, then I'd appreciate your thoughts

**Comment by RogerSelwyn** [comment]
Maybe worth trying this, it is currently set as a receiver.

You can override the device_class in customize.yaml (also possible from the UI somehow):

media_player.living_room_tv:
  device_class: tv

**Comment by snakuzzo** [comment]
I need just to turn on/off the SkyQ.
I tried to use `device_class: tv` but I had this strange behaviour ([video](https://youtu.be/s9AHliYwLFo))
For now I solved creating a [universal media player](https://www.home-assistant.io/integrations/universal/) entity...and I'm exposing this entity

```yaml
media_player:

  - platform: universal
    name: universal_sky
    children:
      - media_player.sky
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.sky
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.sky
```

**Comment by RogerSelwyn** [comment]
Ok, I’ll try and do the same and see what looks different. The pain will be setting up GA because it looks quite complex to get going.

**Comment by snakuzzo** [comment]
It's not complex ;)
There's a [step.-by-step guide](https://www.home-assistant.io/integrations/google_assistant/#google-cloud-platform-configuration).

But...as I said in my first post, I don't know if there is a bug on your side...Google sometimes "makes jokes" :)
Just 2 days ago I had a problem with voice commands on every google home...and yesterday everything started working again, just like a magic!

**Comment by RogerSelwyn** [comment]
OK, I followed the 'step-by-step' guide, which went on for a while. To be honest I have no visibility as to whether it is hooked up or not. When I try to test in the Google Simulator to 'Discover Devices' I just get an 'Invocation Error' which says I can't test standard Google Assistant features in the simulator. So I suspect I need to go out and buy an android phone or some other device to test it. I'm afraid this is edging towards the 'too hard' pile, especially since you have a work around.

**Comment by RogerSelwyn** [comment]
> Maybe worth trying this, it is currently set as a receiver.
> 
> You can override the device_class in customize.yaml (also possible from the UI somehow):
> 
> ```
> media_player.living_room_tv:
>   device_class: tv
> ```

Having installed Google Home on my iPad, the above worked for me and the sky boxes were shown as TVs in Google Home. To me this is wrong, it shouldn't be needed, because the device is correctly listed as a Receiver in HA, and show in Google Home as an AVR. T

he Sonos devices which have no device_class assigned to them in HA seem to work find and show in Google Home as Set Top Boxes.

When setting the above in customize.yaml, don't forget you will then need to include it into your config.

```
homeassistant:
  customize: !include customize.yaml

```

**Comment by snakuzzo** [comment]
I already tried in the pas days.
Tried again few minutes ago with and without `device_class`... no way to control my SkyQ :(

Just a thing...
I create "on demand" my package with `media_player` entity (following your instructions) with a bash script that using SkyQ local API gets all available channels...

```bash
#!/bin/bash
IP="192.168.1.15"
NAME="Sky"
DIR="/config/packages"
FILE_MP="skyq_mediaplayer.yaml"
FILE_CH="skyq_channels.yaml"

echo "Creating/Updating ${DIR}/${FILE_MP} file..."

echo "
media_player:
- platform:  skyq
  name: ${NAME}
  host: ${IP}
  #output_programme_image: False
  live_tv: False
  country: "ITA"
  #generate_switches_for_channels: true
  sources:" > ${DIR}/${FILE_MP}

echo "Getting SkyQ channel list..."

BODYRESPONSE=$(curl -s --location --request GET ${IP}:9006/as/services)

echo "Updating channel list..."

services=$( jq -r '.services' <<< "${BODYRESPONSE}" )

for row in $(echo "${services}" | jq -r '.[] | @base64'); do
    channelName=`echo ${row} | base64 -d | jq -r ${1} '.t' | tr -d ' ' | tr -d \' | sed 's/#//'`
    channelNr=`echo ${row} | base64 -d | jq -r ${1} '.c'`
    channelNrCmd=`echo ${row} | base64 -d | jq -r ${1} '.c' | sed 's/\(.\{1\}\)/\1,/g' | sed 's/.$//'`
    
    echo "    "${channelName}_${channelNr}: \'${channelNrCmd}\' >> ${DIR}/${FILE_MP}

done
echo "Done!"
``` 
this is the "partial" result...

```yaml
media_player:
- platform:  skyq
  name: Sky
  host: 192.168.1.15
  #output_programme_image: False
  live_tv: False
  country: ITA
  #generate_switches_for_channels: true
  sources:
    SkyTG24HD_100: '1,0,0'
    Rai1_101: '1,0,1'
    Rai2_102: '1,0,2'
    Rai3_103: '1,0,3'
    Rete4HD_104: '1,0,4'
    Canale5HD_105: '1,0,5'
    ...
    ...
    ...
    RadioSwissPop_8892: '8,8,9,2'
```

The package include about 730 different channels.
On Home Assistant no problem...everything works fine.
Can this create problems on GH? Consider I'm not exposing channels to GH as switch.
