### ISSUE TITLE
Config Flow not installing/working with 2.2.0

### ISSUE THREAD

**Issue by Gavin-A92** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#6]
**Describe the bug**
I’ve upgraded to the 2.2.0 Alpha 2 (from Alpha 1) and the component works fine as usual but config flow will not work at all.
If I go to Integrations and look to add it I get the “installing component” message but then just back to Integrations without it installing…the yaml configured entities work fine.
Have installed from HACS and tested (without reboot as it didn't ask) and also after rebooting with no changes.

**To Reproduce**
Go to Integrations, click +, select SkyQ and wait.......

**Component versions**
1. 2.2.0 Alpha 2
2. What was the last version where the problem was not shown? 2.1.8

**Your config.yaml**
Not sure it's relevant given the issue is config flow related...yaml configured the component all working fine but let me know if you need it 

**Output of HA logs**
Only reference to SkyQ component apart from the standard "custom" warning is 

`WARNING (MainThread) [custom_components.skyq.media_player] Use of 'config_directory' is deprecated since it is no longer required. You set it to /config/.`

**Comment by RogerSelwyn** [comment]
There was no config_flow in 2.1.8. Rather than upgrading from alpha to alpha2, please uninstall and reinstall. I will test some scenarios of moving from yaml to config_flow, but I’m not intending that you configure the same box via both methods. That is just too complex for now. You can do all the same config via config_flow so just use one or the other for a particular box.

**Comment by Gavin-A92** [comment]
Yeah understand that re 2.1.8.

What I'd taken was that 2.2.0 was an either/or choice for yaml vs config flow.
As I'd mentioned the config flow interface will not launch for me on 2.2.0 (A1 or A2) on numerous browsers/machines.

Will uninstall/reinstall and update you from there

**Comment by Gavin-A92** [comment]
So have removed the component via HACS (and made sure all files/folders removed too), reinstalled and all seems fine in terms of using the config flow.
Can install the Integration and config a Q box without issue.

thanks for all the work on this...cheers
(will leave it to you to close the issue assuming you are happy there isn't one)

**Comment by RogerSelwyn** [comment]
Thanks, I'll investigate when I get a chance away from home duties....

**Comment by RogerSelwyn** [comment]
> When I upgraded to the first alpha (not Alpha 2) it seems that the entities got recreated as _2 using the original yaml config with the original entities now unavailable…didn’t touch the config flow side of things.
> anyway will open issue as per your msg…cheers 

When you did the original upgrade, it shouldn't have create _2 entities. It should have just left the originals intact. Are you saying you did the upgrade, and did no other configurations?

Thanks for your help :-)

**Comment by Gavin-A92** [comment]
Yeah, upgraded and rebooted, that was all.
Didn't notice at the time (as it was late when I updated) but when went back to SkyQ via HA all three boxes were unavailable (but working fine in real life). Did a bit of digging and found 3 new entities, each with "_2" on the name.
As I'd mentioned not an issues per se as easily resolved in HA but just to say it out loud.

![image](https://user-images.githubusercontent.com/32313094/82758277-7127fa00-9ddd-11ea-81e7-c8eca412345c.png)


(Also I've noticed something else with the current Alpha where commands/buttons that have previously worked are not working now and throwing an error in the logs - do you want me to lump that in here too or open a new one)

**Comment by RogerSelwyn** [comment]
Can you create a new issue for the buttons. If you can post the YAML for the items not working, that would help. Or if running from Lovelace via 'play_media' service the post what the config is.

For the upgrade issue, ff you feel like it, have a look in `.storage/core.entity_registry`, and look for the skyq entities. I'm interested in the unique_id for them, in particular the one that is show unavailable (media_player.skyq_office). You can obfuscate the serial numbers if posting here, but just be consistent in what you obfuscate so I can compare. I did change the logic on unique_id slightly, but it should have generated the same thing.

**Comment by Gavin-A92** [comment]
Will do re the buttons issue.......

**Re Upgrade**
The original SkyQ_Office doesn't have (never had) a core.entity_registry entry so no unique_id.....that was the original one from day 1 so when the component was yaml only....the _2 got created only recently (though without any yaml config changes) and without touching config flow either.
TBH it could be a case that my issue is outside the norm.....during all this I've also upgraded to HA 0.110.x and HACS 1.0.x too so maybe the _2 is related there, though as I said no config changes made.
If no one else if reporting I'd not spend huge time on it.

All that said, at the moment if I config via yaml the Integration works fine, but if I disable/comment out  yaml and config via interface the same box shows unavailable. Maybe it's something to do with my IRL box again as against the GBR box you're working off ??

current core.entity_registry
 ```
{
                "connection_class": "local_poll",
                "data": {
                    "host": "192.168.10.242",
                    "name": "SkyQ Office"
                },
                "domain": "skyq",
                "entry_id": "6d16c91e607c44668b90704b29f90760",
                "options": {
                    "generate_switches_for_channels": true,
                    "live_tv": true,
                    "output_programme_image": true,
                    "room": "Office"
                },
                "source": "user",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "SkyQ Office",
                "unique_id": "IRL1234567890c",
                "version": 1
            }
```

here's the working yaml for the same box

```
  - platform: skyq
    host: 192.168.10.242
    name: SkyQ Office
    room: Office
    #config_directory: '/config/'
    generate_switches_for_channels: true
    country: GBR
    sources:
      CHup: 'channelup'
      CHdn: 'channeldown'
      Select: 'select'                                                          
      Up: 'up'                                                                  
      Down: 'down'                                                              
      Left: 'left'                                                              
      Right: 'right'                                                            
      I: 'i'                                                                    
      Dismiss: 'dismiss'                                                        
      Sidebar: 'Sidebar'                                                        
      Home: 'home'                                                              
      TVGuide: 'tvguide'                                                        
      Sky: 'sky'                                                                
      Record: 'record'  
```
