### ISSUE TITLE
After the last HA upgrade core_2021.11.5 error on install The configuration flow cannot be loaded[BUG]

### ISSUE THREAD

**Issue by giugit** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#79]
**Describe the bug**  

I use a custom SkyQ integration that has stop to work with error

Platform error media_player.skyq - cannot import name ‘HTTP_OK’ from ‘homeassistant.const’ (/usr/src/homeassistant/homeassistant/const.py)

---

I tried to install this component but i have this error on install The configuration flow cannot be loaded

Thanks  
 

**To Reproduce**  
1. What were you doing/watching at the time ?
2. What channel were you on?
3. What time did the problem occur?
4. Where are you (bear in mind component supports GBR/ITA at the moment)?

**Expected behavior**  

**Screenshots**  

**Component versions**  
1. What version of SkyQ component are you using?
2. What was the last version where the problem was not shown?

**Your configuration**  
How have you setup your devices, by UI or YAML?

**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  
```yaml
media_player:
 - platform:  skyq
   name: SkyQ Living Room
   host: 192.168.0.10
   live_tv: True
   country: "UK"
   sources:
      SkyOne: '1,0,6'
      SkyNews: '5,0,1'
````
**Output of HA logs**  
Paste the relavant output of the HA log here.

**Additional context**
