### ISSUE TITLE
[BUG]Config flow could not be loaded error

### ISSUE THREAD

**Issue by paulb1803** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#91]
**Describe the bug**  
downloaded with hacs on hasswp. when i try to install, i get the config flow could not be loaded. removed and readded numerous times but no joy unfortunately. is this because im using hasswp rather than a vm etc? 

**To Reproduce**  
1. What were you doing/watching at the time ?
2. What channel were you on?
3. What time did the problem occur?
4. Where are you (bear in mind component supports GBR/ITA at the moment)?

**Expected behavior**  

**Screenshots**  

**Component versions**  
1. What version of SkyQ component are you using?
2. What was the last version where the problem was not shown?

**Your configuration**  
How have you setup your devices, by UI or YAML?

**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  
```yaml
media_player:
 - platform:  skyq
   name: SkyQ Living Room
   host: 192.168.0.10
   live_tv: True
   country: "UK"
   sources:
      SkyOne: '1,0,6'
      SkyNews: '5,0,1'
````
**Output of HA logs**  
Paste the relavant output of the HA log here.

**Additional context**
