### ISSUE TITLE
Error in LOG

### ISSUE THREAD

**Issue by dodor87** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#93]
All works correctly but i've the following error in log :

`2022-02-27 12:31:27 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.skyq_salone fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
  File "/config/custom_components/skyq/media_player.py", line 334, in async_update
    SwitchMaker(
  File "/config/custom_components/skyq/classes/switchmaker.py", line 64, in __init__
    self._add_switch(channel, channel, "select_source", True)
  File "/config/custom_components/skyq/classes/switchmaker.py", line 70, in _add_switch
    source_switch = switch.replace("'", "''")
AttributeError: 'int' object has no attribute 'replace'`

**Expected behavior**  

**Component versions**  
1. What version of SkyQ component are you using?
3. What was the last version where the problem was not shown?

Latest

**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  
```yaml
    
  - platform:  skyq
    name: SkyQ Salone
    host: 192.168.0.161
    generate_switches_for_channels: true
    live_tv: True
    sources:
      CHup: 'channelup'                                                         #added
      CHdn: 'channeldown'                                                       #added
      Select: 'select'                                                          #added
      Up: 'up'                                                                  #added
      Down: 'down'                                                              #added
      Left: 'left'                                                              #added
      Right: 'right'                                                            #added
      I: 'i'                                                                    #added
      Dismiss: 'dismiss'                                                        #added
      Sidebar: 'Sidebar'                                                        #added
      Home: 'home'                                                              #added
      TVGuide: 'tvguide'                                                        #added
      Sky: 'sky'                                                                #added
      Record: 'record'   
      0: '0'
      1: '1'
      2: '2'
      3: '3'
      4: '4'
      5: '5'
      6: '6'
      7: '7'
      8: '8'
      9: '9'
````
